#!/usr/bin/python3

"""
    ============================
    = Plotting GM/R vs r*dU/dr =
    ============================

    Plotting how delta GM/R compares to delta U at different distances

    Uses the data generated by "checking_host_pot_vs_gmr.py"
"""

import utilities as ut
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
import orbit_io
import summary_io
print('Read in the tools')

### Set path and initial parameters
sim_data = orbit_io.OrbitRead(gal1='m12i', location='mac')
print('Set paths')


# Initialize the classes, read in the data, and create data masks
summary = summary_io.SummaryDataSort()
summary_plot = summary_io.SummaryDataPlot()

# Select which mask you want to use and the corresponding directory
directory = sim_data.home_dir+'/orbit_data/plots/summary/paper_2/energy/delta_energy_checks_new'

# Read in all of the data
data_m12b = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/m12b_host_potential_check.hdf5')
data_m12c = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/m12c_host_potential_check.hdf5')
data_m12f = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/m12f_host_potential_check.hdf5')
data_m12i = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/m12i_host_potential_check.hdf5')
data_m12m = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/m12m_host_potential_check.hdf5')
data_m12w = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/m12w_host_potential_check.hdf5')
data_Romeo = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/Romeo_host_potential_check.hdf5')
data_Juliet = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/Juliet_host_potential_check.hdf5')
data_Thelma = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/Thelma_host_potential_check.hdf5')
data_Louise = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/potentials_new/all_snapshots/host_potential_and_gmr/Louise_host_potential_check.hdf5')
ds = np.array([100, 110, 200, 210, 300, 310, 500, 510])
G = ((6.67*10**(-11)*2*10**(30))/(10**3*3.086*10**(16)*1000**2))

"""
    Calculate what GM/R is from the enclosed mass data
"""
def gmr(mass, dist):
    array = np.zeros(len(mass))
    for i in range(0,len(dist)):
        array[i] = ((6.67*10**(-11)*2*10**(30))/(10**3*3.086*10**(16)*1000**2))*mass[i]/dist[i]
    return array

gmr_m12b = gmr(data_m12b['mass.enclosed'], ds)
gmr_m12c = gmr(data_m12c['mass.enclosed'], ds)
gmr_m12f = gmr(data_m12f['mass.enclosed'], ds)
gmr_m12i = gmr(data_m12i['mass.enclosed'], ds)
gmr_m12m = gmr(data_m12m['mass.enclosed'], ds)
gmr_m12w = gmr(data_m12w['mass.enclosed'], ds)
gmr_Romeo = gmr(data_Romeo['mass.enclosed'], ds)
gmr_Juliet = gmr(data_Juliet['mass.enclosed'], ds)
gmr_Thelma = gmr(data_Thelma['mass.enclosed'], ds)
gmr_Louise = gmr(data_Louise['mass.enclosed'], ds)


def r_del_pot(pot, dist):
    array = np.zeros(int(len(pot)/2))
    inds = np.arange(0, len(pot), 2)
    for i in inds:
        array[int(i/2)] = dist[i+1]*2*(pot[i+1]-pot[i])/10 # extra factor of two to account for the incorrect h^2 correction
    return array

u_m12b = r_del_pot(data_m12b['potential'], ds)
u_m12c = r_del_pot(data_m12c['potential'], ds)
u_m12f = r_del_pot(data_m12f['potential'], ds)
u_m12i = r_del_pot(data_m12i['potential'], ds)
u_m12m = r_del_pot(data_m12m['potential'], ds)
u_m12w = r_del_pot(data_m12w['potential'], ds)
u_Romeo = r_del_pot(data_Romeo['potential'], ds)
u_Juliet = r_del_pot(data_Juliet['potential'], ds)
u_Thelma = r_del_pot(data_Thelma['potential'], ds)
u_Louise = r_del_pot(data_Louise['potential'], ds)


"""
    Plot the data at different distances
        - 30 vs 50 kpc
        - 50 vs 100 kpc
        - 100 vs 300 kpc
        - 300 vs 500 kpc
"""
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(2, 2, figsize=(20,18))
#
axs[0,0].scatter(np.abs(u_m12b[0])/1e4, gmr_m12b[1]/1e4, s=150., color=summary_plot.colors[0], alpha=1, label='m12b')
axs[0,0].scatter(np.abs(u_m12c[0])/1e4, gmr_m12c[1]/1e4, s=150., color=summary_plot.colors[1], alpha=1, label='m12c')
axs[0,0].scatter(np.abs(u_m12f[0])/1e4, gmr_m12f[1]/1e4, s=150., color=summary_plot.colors[2], alpha=1, label='m12f')
axs[0,0].scatter(np.abs(u_m12i[0])/1e4, gmr_m12i[1]/1e4, s=150., color=summary_plot.colors[3], alpha=1, label='m12i')
axs[0,0].scatter(np.abs(u_m12m[0])/1e4, gmr_m12m[1]/1e4, s=150., color=summary_plot.colors[4], alpha=1, label='m12m')
axs[0,0].scatter(np.abs(u_m12w[0])/1e4, gmr_m12w[1]/1e4, s=150., color=summary_plot.colors[5], alpha=1, label='m12w')
axs[0,0].scatter(np.abs(u_Romeo[0])/1e4, gmr_Romeo[1]/1e4, s=150., color=summary_plot.colors[6], alpha=1, label='Romeo')
axs[0,0].scatter(np.abs(u_Juliet[0])/1e4, gmr_Juliet[1]/1e4, s=150., color=summary_plot.colors[7], alpha=1, label='Juliet')
axs[0,0].scatter(np.abs(u_Thelma[0])/1e4, gmr_Thelma[1]/1e4, s=150., color=summary_plot.colors[8], alpha=1, label='Thelma')
axs[0,0].scatter(np.abs(u_Louise[0])/1e4, gmr_Louise[1]/1e4, s=150., color=summary_plot.colors[9], alpha=1, label='Louise')
#
axs[0,1].scatter(np.abs(u_m12b[1])/1e4, gmr_m12b[3]/1e4, s=150., color=summary_plot.colors[0], alpha=1, label='m12b')
axs[0,1].scatter(np.abs(u_m12c[1])/1e4, gmr_m12c[3]/1e4, s=150., color=summary_plot.colors[1], alpha=1, label='m12c')
axs[0,1].scatter(np.abs(u_m12f[1])/1e4, gmr_m12f[3]/1e4, s=150., color=summary_plot.colors[2], alpha=1, label='m12f')
axs[0,1].scatter(np.abs(u_m12i[1])/1e4, gmr_m12i[3]/1e4, s=150., color=summary_plot.colors[3], alpha=1, label='m12i')
axs[0,1].scatter(np.abs(u_m12m[1])/1e4, gmr_m12m[3]/1e4, s=150., color=summary_plot.colors[4], alpha=1, label='m12m')
axs[0,1].scatter(np.abs(u_m12w[1])/1e4, gmr_m12w[3]/1e4, s=150., color=summary_plot.colors[5], alpha=1, label='m12w')
axs[0,1].scatter(np.abs(u_Romeo[1])/1e4, gmr_Romeo[3]/1e4, s=150., color=summary_plot.colors[6], alpha=1, label='Romeo')
axs[0,1].scatter(np.abs(u_Juliet[1])/1e4, gmr_Juliet[3]/1e4, s=150., color=summary_plot.colors[7], alpha=1, label='Juliet')
axs[0,1].scatter(np.abs(u_Thelma[1])/1e4, gmr_Thelma[3]/1e4, s=150., color=summary_plot.colors[8], alpha=1, label='Thelma')
axs[0,1].scatter(np.abs(u_Louise[1])/1e4, gmr_Louise[3]/1e4, s=150., color=summary_plot.colors[9], alpha=1, label='Louise')
#
axs[1,0].scatter(np.abs(u_m12b[2])/1e4, gmr_m12b[5]/1e4, s=150., color=summary_plot.colors[0], alpha=1, label='m12b')
axs[1,0].scatter(np.abs(u_m12c[2])/1e4, gmr_m12c[5]/1e4, s=150., color=summary_plot.colors[1], alpha=1, label='m12c')
axs[1,0].scatter(np.abs(u_m12f[2])/1e4, gmr_m12f[5]/1e4, s=150., color=summary_plot.colors[2], alpha=1, label='m12f')
axs[1,0].scatter(np.abs(u_m12i[2])/1e4, gmr_m12i[5]/1e4, s=150., color=summary_plot.colors[3], alpha=1, label='m12i')
axs[1,0].scatter(np.abs(u_m12m[2])/1e4, gmr_m12m[5]/1e4, s=150., color=summary_plot.colors[4], alpha=1, label='m12m')
axs[1,0].scatter(np.abs(u_m12w[2])/1e4, gmr_m12w[5]/1e4, s=150., color=summary_plot.colors[5], alpha=1, label='m12w')
axs[1,0].scatter(np.abs(u_Romeo[2])/1e4, gmr_Romeo[5]/1e4, s=150., color=summary_plot.colors[6], alpha=1, label='Romeo')
axs[1,0].scatter(np.abs(u_Juliet[2])/1e4, gmr_Juliet[5]/1e4, s=150., color=summary_plot.colors[7], alpha=1, label='Juliet')
axs[1,0].scatter(np.abs(u_Thelma[2])/1e4, gmr_Thelma[5]/1e4, s=150., color=summary_plot.colors[8], alpha=1, label='Thelma')
axs[1,0].scatter(np.abs(u_Louise[2])/1e4, gmr_Louise[5]/1e4, s=150., color=summary_plot.colors[9], alpha=1, label='Louise')
#
axs[1,1].scatter(np.abs(u_m12b[3])/1e4, gmr_m12b[7]/1e4, s=150., color=summary_plot.colors[0], alpha=1, label='m12b')
axs[1,1].scatter(np.abs(u_m12c[3])/1e4, gmr_m12c[7]/1e4, s=150., color=summary_plot.colors[1], alpha=1, label='m12c')
axs[1,1].scatter(np.abs(u_m12f[3])/1e4, gmr_m12f[7]/1e4, s=150., color=summary_plot.colors[2], alpha=1, label='m12f')
axs[1,1].scatter(np.abs(u_m12i[3])/1e4, gmr_m12i[7]/1e4, s=150., color=summary_plot.colors[3], alpha=1, label='m12i')
axs[1,1].scatter(np.abs(u_m12m[3])/1e4, gmr_m12m[7]/1e4, s=150., color=summary_plot.colors[4], alpha=1, label='m12m')
axs[1,1].scatter(np.abs(u_m12w[3])/1e4, gmr_m12w[7]/1e4, s=150., color=summary_plot.colors[5], alpha=1, label='m12w')
axs[1,1].scatter(np.abs(u_Romeo[3])/1e4, gmr_Romeo[7]/1e4, s=150., color=summary_plot.colors[6], alpha=1, label='Romeo')
axs[1,1].scatter(np.abs(u_Juliet[3])/1e4, gmr_Juliet[7]/1e4, s=150., color=summary_plot.colors[7], alpha=1, label='Juliet')
axs[1,1].scatter(np.abs(u_Thelma[3])/1e4, gmr_Thelma[7]/1e4, s=150., color=summary_plot.colors[8], alpha=1, label='Thelma')
axs[1,1].scatter(np.abs(u_Louise[3])/1e4, gmr_Louise[7]/1e4, s=150., color=summary_plot.colors[9], alpha=1, label='Louise')
#
axs[0,0].plot([2,4],[2,4], color='k', alpha=0.8)
axs[0,1].plot([1.2,3],[1.2,3], color='k', alpha=0.8)
axs[1,0].plot([0.6,2.2],[0.6,2.2], color='k', alpha=0.8)
axs[1,1].plot([0,2.9],[0,2.9], color='k', alpha=0.8)
#
axs[0,0].set_xlim(2,4)
axs[0,0].set_ylim(2.2,3.4)
axs[0,1].set_xlim(1.2,3)
axs[0,1].set_ylim(1.7,2.65)
axs[1,0].set_xlim(0.6,2)
axs[1,0].set_ylim(1.4,2.2)
axs[1,1].set_xlim(0,2.9)
axs[1,1].set_ylim(1.05, 1.65)
#
axs[0,0].set_xlabel('$110\ kpc \\times |\\Phi(110\ kpc) - \\Phi(100\ kpc)| /$ 10 kpc [10$^4$ km$^2$ s$^{-2}$]', fontsize=20)
axs[0,1].set_xlabel('$210\ kpc \\times |\\Phi(210\ kpc) - \\Phi(200\ kpc)| /$ 10 kpc [10$^4$ km$^2$ s$^{-2}$]', fontsize=20)
axs[1,0].set_xlabel('$310\ kpc \\times |\\Phi(310\ kpc) - \\Phi(300\ kpc)| /$ 10 kpc [10$^4$ km$^2$ s$^{-2}$]', fontsize=20)
axs[1,1].set_xlabel('$510\ kpc \\times |\\Phi(510\ kpc) - \\Phi(500\ kpc)| /$ 10 kpc [10$^4$ km$^2$ s$^{-2}$]', fontsize=20)
#
axs[0,0].set_ylabel('GM/R(<110 kpc) [10$^4$ km$^2$ s$^{-2}$]', fontsize=20)
axs[0,1].set_ylabel('GM/R(<210 kpc) [10$^4$ km$^2$ s$^{-2}$]', fontsize=20)
axs[1,0].set_ylabel('GM/R(<310 kpc) [10$^4$ km$^2$ s$^{-2}$]', fontsize=20)
axs[1,1].set_ylabel('GM/R(<510 kpc) [10$^4$ km$^2$ s$^{-2}$]', fontsize=20)
#
axs[0,0].tick_params(axis='both', which='both', bottom=True, top=True, labelsize=18)
axs[0,1].tick_params(axis='both', which='both', bottom=True, top=True, labelsize=18)
axs[1,0].tick_params(axis='both', which='both', bottom=True, top=True, labelsize=18)
axs[1,1].tick_params(axis='both', which='both', bottom=True, top=True, labelsize=18)
#
axs[0,0].legend(prop={'size': 20}, ncol=2, loc='best')
#
plt.tight_layout()
plt.savefig(directory+'/delta_gmr_vs_r_dphi_dr.pdf')
plt.close()
