#!/usr/bin/python3

"""
    ====================
    = Paper III ORBITS =
    ====================

    Plot the actual orbits of subhalo analogs of satellites.

"""

# Import packages
import orbit_io
import halo_analysis as halo
import gizmo_analysis as gizmo
import utilities as ut
import numpy as np
import pandas as pd
import satellite_io
import matplotlib
from matplotlib import pyplot as plt
import matplotlib.patches as mpatches
import time
print('Read in the tools')

### Set path and initial parameters
loc = 'mac'
sim_data = satellite_io.SatelliteRead(gal1='m12i', location=loc)
sat_analysis = satellite_io.SatelliteAnalysis(gal1='m12i', location=loc)
#
print('Set paths')

# Read in the snapshot dictionary and the entire tree
lg_data = pd.read_csv(sim_data.home_dir+'/orbit_data/paper_III/localgroup_galaxies_condensed.csv', index_col=0)

galaxies = ['m12b', 'm12c', 'm12f', 'm12i', 'm12m', 'm12n', 'm12q', 'm12w', 'Romeo', 'Juliet', 'Thelma', 'Louise', 'Romulus', 'Remus']

mw_sats_1Mpc =     ['Antlia II', 'Aquarius II', 'Aquarius III', 'Bootes I', 'Bootes II', 'Bootes III', \
                    'Bootes IV', 'Bootes V', 'Canes Venatici I', 'Canes Venatici II', 'Carina', 'Carina II', \
                    'Carina III', 'Centaurus I', 'Cetus II', 'Cetus III', 'Columba I', 'Coma Berenices', \
                    'Crater II', 'Draco', 'Draco II', 'Eridanus II', 'Eridanus III', 'Eridanus IV', \
                    'Fornax', 'Grus I', 'Grus II', 'Hercules', 'Horologium I', 'Horologium II', \
                    'Hydra II', 'Hydrus I', 'Indus I', 'Leo I', 'Leo II', 'Leo IV', \
                    'Leo V', 'Leo VI', 'Leo A', 'Leo T', 'Leo Minor I', 'Pegasus III', \
                    'Pegasus IV', 'Phoenix I', 'Phoenix II', 'Pictor I', 'Pictor II', 'Pisces II', \
                    'Reticulum II', 'Reticulum III', 'Sagittarius', 'Sagittarius II', 'Sculptor', 'Segue 1', \
                    'Segue 2', 'Sextans', 'Sextans II', 'Triangulum II', 'Tucana I', 'Tucana II', \
                    'Tucana III', 'Tucana IV', 'Tucana V', 'Ursa Major I', 'Ursa Major II', 'Ursa Minor', \
                    'Virgo I', 'Virgo II', 'Virgo III', 'Willman 1']

n_555 = [12, 330, 378, 83, 131, 3, 2, 305, 42, 213, 15, 13, 75, 89, 125, 5, 243, 153, 43, 13, 26, 57, 4, 125, 4, 99, 99, 111, 163, 301, 212, 49, 52, 0, 25, 167, 255, 347, 18, 67, 517, 362, 178, 13, 387, 127, 77, 363, 104, 954, 2, 107, 4, 103, 20, 12, 42, 17, 15, 151, 0, 183, 113, 193, 261, 20, 62, 87, 45, 53]

redShift = 7
reionDists = []
sat_mstar = []
sat_dist = []

#
for sat_idx, galaxy in enumerate(mw_sats_1Mpc):
    satellite_name = galaxy.replace(' ', '_')
    if n_555[sat_idx] < 10:
        file_path_read = sim_data.home_dir+f'/orbit_data/hdf5_files/satellite_matching/combined_physical_tweaks/floor_10_10_10/weights_{satellite_name}.txt'
    else:
        file_path_read = sim_data.home_dir+f'/orbit_data/hdf5_files/satellite_matching/combined_physical_tweaks/floor_5_5_5/weights_{satellite_name}.txt'
    #
    gal_data = sat_analysis.read_subhalo_matches(galaxy, file_path_read)
    mini_data = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/summary_data/data_'+'m12i'+'_all_subhalos', verbose=False)
    sat_match = satellite_io.SatelliteMatch(tree=None, mini=mini_data, gal1='m12i', location=loc)
    match = sat_match.lg_satellite_properties(lg_data=lg_data, galaxy_name=galaxy, mass_err=0.35)
    #
    sat_mstar.append(lg_data[galaxy]['mass.star'])
    sat_dist.append(lg_data[galaxy]['host.distance.total'])

    redData = (-1)*np.ones(gal_data.shape[0])
    #redData = []
    #
    for name in galaxies:
        mini_data = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/summary_data/data_'+name+'_all_subhalos', verbose=False)
        snaps = ut.simulation.read_snapshot_times(directory=sim_data.home_dir+'/galaxies/snapshot_times/'+name)
        #
        reionInd = np.where(np.min(np.abs(snaps['redshift'] - redShift)) == np.abs(snaps['redshift'] - redShift))[0][0]
        deltaT = snaps['time'][-1] - snaps['time'][reionInd]
        #
        # get the matches for a simulation host
        mask = (gal_data['Host'] == name)
        # get an array of the tree indices that are matches in m12m
        subhalo_inds = np.asarray(gal_data['Halo tree index'][mask])
        # Get indices within the mini data to select properties
        mini_data_match_inds = np.asarray([np.where(i == mini_data['indices.z0'][:,0])[0][0] for i in subhalo_inds])
        #
        if len(mini_data_match_inds) != 0:
            # Snapshot at match
            snap_at_match = snaps['index'][gal_data['Snapshot at match'][mask]]
            timeAtReion = snaps['time'][snap_at_match] - deltaT
            maskReion = (timeAtReion >= 0)
            #
            host_rows = np.where(mask)[0]
            target_rows = host_rows[maskReion]
            #
            for i in range(np.sum(maskReion)):
                #
                reionIndP = np.where(np.min(np.abs(snaps['time'] - timeAtReion[maskReion][i])) == np.abs(snaps['time'] - timeAtReion[maskReion][i]))[0][0]
                reionIndP2 = reionIndP - (len(snaps['time']) - mini_data['d.tot.sim'].shape[1]) # need to account for the fact that the distance arrays aren't all 601 length (or 501)
                #
                redData[target_rows[i]] = np.flip(mini_data['d.tot.sim'][mini_data_match_inds[maskReion]][i])[reionIndP2]
                #redData.append(np.flip(mini_data['d.tot.sim'][mini_data_match_inds[maskReion]][i])[reionIndP2])
                #
    mask_null = (redData != -1)
    if np.sum(mask_null) != 0:
        x_med = ut.math.percentile_weighted(redData[mask_null], 50, gal_data['Weight'][mask_null])
        x_lower = ut.math.percentile_weighted(redData[mask_null], 15.87, gal_data['Weight'][mask_null])
        x_upper = ut.math.percentile_weighted(redData[mask_null], 84.13, gal_data['Weight'][mask_null])
        reionDists.append((x_med, x_lower, x_upper))
    else:
        reionDists.append((-1,-1,-1))

"""
    Plot the shifted physical distances
"""
reionDists = np.asarray(reionDists)
sat_mstar = np.asarray(sat_mstar)
sat_dist = np.asarray(sat_dist)
mask = (reionDists[:,0] >= 0)
meds = reionDists[:,0]
lowers = reionDists[:,1]
uppers = reionDists[:,2]

# Vs Mstar
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_mstar[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_mstar[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xscale('log')
axs.set_xlabel('$M_{\\rm star}$ [$M_{\odot}$]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc physical]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_shifted_vs_mstar.pdf')
plt.close()

# Vs distance
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xlim(xmin=0)
axs.set_xlabel('Distance at $z = 0$ [kpc]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc physical]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_shifted_vs_dist.pdf')
plt.close()

# Vs distance (zoom)
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xlim(xmin=0, xmax=430)
axs.set_xlabel('Distance at $z = 0$ [kpc]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc physical]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_shifted_vs_dist_zoom.pdf')
plt.close()

"""
    Plot the shifted co-moving distances
"""
reionDists_comoving = reionDists*(1+redShift)

mask = (reionDists_comoving[:,0] >= 0)
meds = reionDists_comoving[:,0]
lowers = reionDists_comoving[:,1]
uppers = reionDists_comoving[:,2]

# Vs Mstar
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_mstar[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_mstar[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xscale('log')
axs.set_xlabel('$M_{\\rm star}$ [$M_{\odot}$]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc comoving]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_shifted_comoving_vs_mstar.pdf')
plt.close()

# Vs distance
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xlim(xmin=0)
axs.set_xlabel('Distance at $z = 0$ [kpc physical]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc comoving]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_shifted_comoving_vs_dist.pdf')
plt.close()

# Vs distance (zoom)
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xlim(xmin=0, xmax=430)
axs.set_xlabel('Distance at $z = 0$ [kpc physical]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc comoving]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_shifted_comoving_vs_dist_zoom.pdf')
plt.close()




reionDists = []
frac_exist = []
sat_mstar = []
sat_dist = []

#
for sat_idx, galaxy in enumerate(mw_sats_1Mpc):
    satellite_name = galaxy.replace(' ', '_')
    if n_555[sat_idx] < 10:
        file_path_read = sim_data.home_dir+f'/orbit_data/hdf5_files/satellite_matching/combined_physical_tweaks/floor_10_10_10/weights_{satellite_name}.txt'
    else:
        file_path_read = sim_data.home_dir+f'/orbit_data/hdf5_files/satellite_matching/combined_physical_tweaks/floor_5_5_5/weights_{satellite_name}.txt'
    #
    gal_data = sat_analysis.read_subhalo_matches(galaxy, file_path_read)
    mini_data = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/summary_data/data_'+'m12i'+'_all_subhalos', verbose=False)
    sat_match = satellite_io.SatelliteMatch(tree=None, mini=mini_data, gal1='m12i', location=loc)
    match = sat_match.lg_satellite_properties(lg_data=lg_data, galaxy_name=galaxy, mass_err=0.35)
    #
    sat_mstar.append(lg_data[galaxy]['mass.star'])
    sat_dist.append(lg_data[galaxy]['host.distance.total'])

    redData = (-1)*np.ones(gal_data.shape[0])
    #
    for name in galaxies:
        mini_data = ut.io.file_hdf5(sim_data.home_dir+'/orbit_data/hdf5_files/summary_data/data_'+name+'_all_subhalos', verbose=False)
        snaps = ut.simulation.read_snapshot_times(directory=sim_data.home_dir+'/galaxies/snapshot_times/'+name)
        #
        reionInd = np.where(np.min(np.abs(snaps['redshift'] - redShift)) == np.abs(snaps['redshift'] - redShift))[0][0]
        #
        # get the matches for a simulation host
        mask = (gal_data['Host'] == name)
        # get an array of the tree indices that are matches in m12m
        subhalo_inds = np.asarray(gal_data['Halo tree index'][mask])
        # Get indices within the mini data to select properties
        mini_data_match_inds = np.asarray([np.where(i == mini_data['indices.z0'][:,0])[0][0] for i in subhalo_inds])
        #
        if len(mini_data_match_inds) != 0:
            # Snapshot at match
            snap_at_match = snaps['index'][gal_data['Snapshot at match'][mask]]
            #
            host_rows = np.where(mask)[0]
            target_rows = host_rows
            #
            for i in range(len(host_rows)):
                #
                reionIndP = reionInd - (len(snaps['time']) - mini_data['d.tot.sim'].shape[1])
                redData[target_rows[i]] = np.flip(mini_data['d.tot.sim'][mini_data_match_inds][i])[reionIndP]
                #
    mask_null = (redData != -1)
    if np.sum(mask_null) != 0:
        x_med = ut.math.percentile_weighted(redData[mask_null], 50, gal_data['Weight'][mask_null])
        x_lower = ut.math.percentile_weighted(redData[mask_null], 15.87, gal_data['Weight'][mask_null])
        x_upper = ut.math.percentile_weighted(redData[mask_null], 84.13, gal_data['Weight'][mask_null])
        reionDists.append((x_med, x_lower, x_upper))
    else:
        reionDists.append((-1,-1,-1))
    #
    frac_exist.append(np.sum(mask_null)/(np.sum(~mask_null) + np.sum(mask_null)))

"""
    Plot the non-shifted physical distances
"""
reionDists = np.asarray(reionDists)
sat_mstar = np.asarray(sat_mstar)
sat_dist = np.asarray(sat_dist)
mask = (reionDists[:,0] >= 0)
meds = reionDists[:,0]
lowers = reionDists[:,1]
uppers = reionDists[:,2]

# Vs Mstar
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_mstar[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_mstar[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xscale('log')
axs.set_xlabel('$M_{\\rm star}$ [$M_{\odot}$]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc physical]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_nonshifted_vs_mstar.pdf')
plt.close()

# Vs distance
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xlim(xmin=0)
axs.set_xlabel('Distance at $z = 0$ [kpc]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc physical]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_nonshifted_vs_dist.pdf')
plt.close()

# Vs distance (zoom)
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xlim(xmin=0, xmax=430)
axs.set_xlabel('Distance at $z = 0$ [kpc]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc physical]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_nonshifted_vs_dist_zoom.pdf')
plt.close()

"""
    Plot the shifted co-moving distances
"""
reionDists_comoving = reionDists*(1+redShift)

mask = (reionDists_comoving[:,0] >= 0)
meds = reionDists_comoving[:,0]
lowers = reionDists_comoving[:,1]
uppers = reionDists_comoving[:,2]

# Vs Mstar
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_mstar[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_mstar[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xscale('log')
axs.set_xlabel('$M_{\\rm star}$ [$M_{\odot}$]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc comoving]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_nonshifted_comoving_vs_mstar.pdf')
plt.close()

# Vs distance
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xlim(xmin=0)
axs.set_xlabel('Distance at $z = 0$ [kpc physical]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc comoving]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_nonshifted_comoving_vs_dist.pdf')
plt.close()

# Vs distance (zoom)
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 1, figsize=(10,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs.errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs.scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
axs.set_xlim(xmin=0, xmax=430)
axs.set_xlabel('Distance at $z = 0$ [kpc physical]', fontsize=24)
axs.set_ylabel(f'Distance at $z = {redShift}$ [kpc comoving]', fontsize=24)
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_nonshifted_comoving_vs_dist_zoom.pdf')
plt.close()











LMC_idxs = [11, 12, 28, 31, 44, 48]


"""
    Plot the non-shifted co-moving data
"""
reionDists = np.asarray(reionDists)
sat_mstar = np.asarray(sat_mstar)
sat_dist = np.asarray(sat_dist)
mask = (reionDists[:,0] >= 0)
meds = reionDists[:,0]
lowers = reionDists[:,1]
uppers = reionDists[:,2]

reionDists_comoving = reionDists*(1+redShift)

mask = (reionDists_comoving[:,0] >= 0)
meds = reionDists_comoving[:,0]
lowers = reionDists_comoving[:,1]
uppers = reionDists_comoving[:,2]


# Vs Mstar
plt.rcParams["font.family"] = "serif"
f, axs = plt.subplots(1, 2, figsize=(16,8))
#
for i in range(0, len(sat_mstar[mask])):
    axs[0].errorbar(sat_dist[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs[0].scatter(sat_dist[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)

for i in range(0, len(sat_mstar[mask])):
    axs[1].errorbar(sat_mstar[mask][i], meds[mask][i], yerr=np.array([[meds[mask][i]-lowers[mask][i]],[uppers[mask][i]-meds[mask][i]]]), color='#c76438', alpha=0.7, lw=3.5, capsize=0)
    axs[1].scatter(sat_mstar[mask][i], meds[mask][i], s=50, c='#c76438', alpha=0.7)
#
for i in LMC_idxs:
    #
    x_dist = sat_dist[i]
    x_mstar = sat_mstar[i]
    y = meds[i]
    yerr = np.array([[y - lowers[i]], [uppers[i] - y]])
    #
    axs[0].errorbar(x_dist, y, yerr=yerr, color='k', lw=3.5, capsize=0, zorder=6, alpha=0.7)
    axs[0].scatter(x_dist, y, s=50, marker='*', color='k', edgecolor='k', zorder=7, alpha=0.7)

    # --- Stellar mass panel (right) ---
    axs[1].errorbar(x_mstar, y, yerr=yerr, color='k', lw=3.5, capsize=0, zorder=6, alpha=0.7)
    axs[1].scatter(x_mstar, y, s=50, marker='*', color='k', edgecolor='k', zorder=7, alpha=0.7)
#
axs[0].set_xlim(0,425)
#
axs[1].set_xscale('log')
#
axs[0].set_xlabel('Distance from MW [kpc]', fontsize=24)
axs[1].set_xlabel('$M_{\\rm star}$ [$M_{\odot}$]', fontsize=24)
axs[0].set_ylabel(f'Distance at $z = {redShift}$ [kpc comoving]', fontsize=24)
#
axs[0].tick_params(axis='both', which='both', bottom=True, top=True, labelsize=22, labelbottom=True)
axs[1].tick_params(axis='both', which='both', bottom=True, top=True, labelsize=22, labelbottom=True, labelleft=False)
#
plt.tight_layout()
#plt.show()
plt.savefig(sim_data.home_dir+'/orbit_data/plots/summary/paper_3/histories/summary_1Mpc/dreion_plot_LMC_marked.pdf')
plt.close()